### ISSUE TITLE
关于 setContents 的问题

### ISSUE THREAD

**Issue by ghost** [textbus/textbus#10]
## 影响版本

公测版 0.1.0-alpha.6

## 复现步骤

1. 当调用 editor.setContents() 时，编辑区域会变成 undefined。

![image](https://user-images.githubusercontent.com/74443578/99410348-561de900-292d-11eb-9b05-54cad4e6412a.png)

此时再次调用 editor.getContents() 时，返回值为

```json
{
  "styleSheets": [此处内容与问题描述无关],
  "content": "undefined<p><br></p>"
}
```

2. 调用 setContents() 方法之后，Ctrl+A 选中编辑区域全部内容，之后按 Delete 键，此时光标会在第二行。按一次上方向键，再按一次下方向键。会报如下错误：

```js
textbus.min.js:24 Uncaught TypeError: Cannot read property 'getContext' of undefined
```

之后再按一次上方向按键，会报如下错误：

```js
textbus.min.js:24 Uncaught Error: DOM 与虚拟节点不同步！
```

此时屏幕光标闪动，但无法输入内容。当编辑区域失去焦点后，无法再次获得焦点。

## 演示

** 请点击图片查看演示详情。由于录屏生成 gif 设置成了只播放一次，因此可能看到的是播放完成不动的画面 **

![1](https://user-images.githubusercontent.com/74443578/99414150-8071a580-2931-11eb-880f-fe65caf5de39.gif)

**Comment by tbhuabi** [comment]
感谢你提出的问题，当前问题已修复。请更新至版本 @tanbo/textbus@0.1.0-alpha.7
