### ISSUE TITLE
支持vue2吗，想使用多人协作功能

### ISSUE THREAD

**Issue by A-ANing** [textbus/textbus#100]

**Comment by textbus** [comment]
Textbus 可以与任意前端框架结合，3.0 有开发一个相对可用的编辑器。
```
npm install @textbus/editor
```

Textbus 4.0 放弃了内核渲染能力，采用框架直接渲染，目前只支持 Viewfly、React、Vue3 以 setup 形式开发视图组件。目前基于 4.0 内核的编辑器还在开发中，你可以关注这个项目：https://github.com/textbus/xnote

**Comment by textbus** [comment]
太过久远了，欢迎关注新版动态
