### ISSUE TITLE
3.7.0，uploader方法怎么自定义打开本地文件

### ISSUE THREAD

**Issue by io-o** [textbus/textbus#101]
![image](https://github.com/textbus/textbus/assets/22197685/229f667b-bc54-47fe-8f55-b500906ba2fa)

如图所示，点击上传 是个button，怎么触发input  file事件，上传文件?

**Comment by textbus** [comment]
点击这个按钮，会触发配置项里的 uploader 方法，你可以在这里创建一个 file input,然后调用 input 的 click 方法，并监听 change 事件，就可以拿到本地文件了

**Comment by textbus** [comment]
太过久远了，欢迎关注新版动态
