### ISSUE TITLE
Textbus内置diff算法咨询

### ISSUE THREAD

**Issue by yaoyaowcs** [textbus/textbus#104]
查阅Textbus资料，看到有些推文说Textbus内置了diff算法，但并无详细介绍。想咨询下Textbus是否真的内置了diff算法，可支持文本内容差异性比较功能的扩展开发。如果可以支持，请问可以在官方文档里补充使用说明吗？如果不能，请问后续有扩展该功能的计划吗？

**Comment by textbus** [comment]
diff 算法主要是给渲染用的，从4.0 开始，textbus 改为用前端框架来渲染，所以内核不需要了。文本差异比较这个可以写专门的算法来处理。只早需要考虑一下大数据量下的性能问题
