### ISSUE TITLE
vue3 的setup语法糖支持吗？有示例吗？

### ISSUE THREAD

**Issue by dengsong666** [textbus/textbus#107]

**Comment by textbus** [comment]
demo 已更新，可参考这里：
https://github.com/textbus/vue-demo/blob/master/src/components/paragraph/paragraph.view.vue
希望能帮助到你。

Vue 的适配还没有完全完成，有一些问题，相对来说，React 和 Viewfly 可以放心使用。 textbus 要完成 vue 的适配，还有一些问题要解决，可参考：https://github.com/vuejs/core/issues/11087

**Comment by textbus** [comment]
你好，vue 最新版本已可正常使用，需升级 vue 版本到 3.4.28。
demo 已更新。https://github.com/textbus/vue-demo
