### ISSUE TITLE
编辑器

### ISSUE THREAD

**Issue by 1004834495** [textbus/textbus#109]
4.0版本如何在上方显示默认编辑器

**Comment by textbus** [comment]
请把问题再描述得具体一点，4.0 官方提供的编辑器是 xnote，仓库地址：https://github.com/textbus/xnote

**Comment by 1004834495** [comment]
这样的默认编辑栏现在怎么配置

**Comment by 1004834495** [comment]
![微信截图_20240708091521](https://github.com/textbus/textbus/assets/131008103/0cb31fef-9536-4c6c-a56e-077ad61e9216)
这样的默认编辑器如何展示

**Comment by textbus** [comment]
> ![微信截图_20240708091521](https://private-user-images.githubusercontent.com/131008103/346397730-0cb31fef-9536-4c6c-a56e-077ad61e9216.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NzQ0NjksIm5iZiI6MTcyMDU3NDE2OSwicGF0aCI6Ii8xMzEwMDgxMDMvMzQ2Mzk3NzMwLTBjYjMxZmVmLTk1MzYtNGM2Yy1hNTZlLTA3N2FkNjFlOTIxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQwMTE2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MGY2MjM0Y2ZlMzRiYzJjOTVkOTRmMjg4YTU0ZjE4ZDdkNDI2YjhhMjRlNzU3NjkxZWQ3ZTM0Nzg1YzY3YTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nwEpqLRhRTs_3bq9oFnFcK5erp8h6b18UXdqfy0pDwU) 这样的默认编辑器如何展示

这个是3.0 的编辑器，4.0 是 xnote，并且大概率不会提供这种形态的编辑器了
