### ISSUE TITLE
针对复制来的内容，编辑时处理有乱码问题

### ISSUE THREAD

**Issue by ghost** [textbus/textbus#13]
从别的页面中复制内容，放入编辑器内，直接保存，展示时可以正常展示，但是编辑时就显示乱码了，

PS：粘贴内容在附件中
[testText.txt](https://github.com/tbhuabi/textbus/files/5613662/testText.txt)

**Comment by tbhuabi** [comment]
请详细描述一下复现步骤。
我测试未出现乱码问题，测试方法：
1、我下载了你的文本文件，保存为 html
2、然后在浏览器打开，然后全选并copy所有内容
3、粘贴进 Textbus
4、随意在任意位置编辑
然后发现可以正常编辑，并无报错或乱码
