### ISSUE TITLE
在内容输入区，选中某段文本之后，进行插入表情、CSS等操作会报错且无效

### ISSUE THREAD

**Issue by ghost** [textbus/textbus#14]
在内容输入区，选中某段文本之后，进行插入表情、CSS等操作会报错且无效。

![www alltoall net_20201204-181120_wVvySxuOUr](https://user-images.githubusercontent.com/58690804/101151965-5d4b3380-365d-11eb-8852-c7d3fbd3d1dc.gif)

**Comment by tbhuabi** [comment]
问题已修复，修复版本：@tanbo/textbus@1.0.0-alpha.6
因为这一段时间忙着重构基础架构，所以没有及时更改，见谅
