### ISSUE TITLE
文档错误 https://textbus.tanboui.com/ 

### ISSUE THREAD

**Issue by ghost** [textbus/textbus#15]
使用版本：`"@tanbo/textbus": "^1.0.0-alpha.4"`

网站首页文档：`const {contents, styleSheets} = editor.getContents();`

经过测试应为：`const {content, styleSheets} = editor.getContents();`

![image](https://user-images.githubusercontent.com/15623549/102680746-09f8e980-41f6-11eb-9231-87fbbf06749f.png)

**Comment by tbhuabi** [comment]
谢谢提醒，已修改
