### ISSUE TITLE
Vue 项目切换路由页面后无法编辑内容

### ISSUE THREAD

**Issue by ghost** [textbus/textbus#16]
使用版本：`"@tanbo/textbus": "^1.0.0-alpha.5",`
操作步骤：
 - 打开编辑器页面
 - 切换到其它页面（不是a标签跳转，而且vue 路由切换）
 - 在进入到编辑器页面（vue路由切换）
编辑器内容无法编辑，但是图片大小可以调整

**Comment by tbhuabi** [comment]
已修复，修复版本@tanbo/textbus@1.0.0-alpha.8
