### ISSUE TITLE
标题 H1-H6 在编辑内渲染出来的大小与直接渲染出来的大小不一致

### ISSUE THREAD

**Issue by ghost** [textbus/textbus#18]
不知道是不是编辑器的不足，请老哥酌情处理

**Comment by tbhuabi** [comment]
这个和具体的页面 css 样式有关，TextBus 使用的浏览器默认的样式。你可以在你的页面上通过css 设置相关样式。
如果你一定要要求 TextBus 的样式和你最终页面的样式一致，可以在初始化 TextBus 时，通过配置项 options.styleSheets 字段设置编辑器内文档的样式。并在你最终页面上使用相同的样式即可。
