### ISSUE TITLE
feature request : 建议针对文件增加 dataset 或者其它属性设置功能

### ISSUE THREAD

**Issue by ghost** [textbus/textbus#20]
由于业务系统需要针对文件进行权限管理所有建议开放该类属性的设置，方便后端解析与获取。

**Comment by tbhuabi** [comment]
一般情况，建议通过直接重写组件类的部分方法实现，如果不能实现需求，建议你自实现相应组件即可。
TextBus 官方提供的组件只有常见的功能，不涉及具体业务层面，因为不能穷举所有需求，对A很重要的功能，对B来说，可能完全是冗余的。
