### ISSUE TITLE
直接在页面引用min.js, chrome运行, 找不到方法 Reflect.getMetadata, 页面空白

### ISSUE THREAD

**Issue by zuozuoba** [textbus/textbus#31]
textbus.min.js:1 Uncaught TypeError: Reflect.getMetadata is not a function
    at textbus.min.js:1

**Comment by tbhuabi** [comment]
问题已修复，请从官网下载更新版本

**Comment by tbhuabi** [comment]
问题已修复，请从官网下载更新版本
