### ISSUE TITLE
直接引用js, 定制toolbar时出错

### ISSUE THREAD

**Issue by zuozuoba** [textbus/textbus#32]
`var editor = textbus.createEditor(document.getElementById('editor'),{
      toolbar:[
        ['historyBackTool', 'historyForwardTool'],
        ['insertObjectTool'],
        ['headingTool'],
        ['boldTool', 'italicTool', 'strikeThroughTool', 'underlineTool'],
        ['olTool', 'ulTool'],
        ['fontSizeTool', 'textIndentTool','textAlignTool'],
        ['colorTool', 'textBackgroundTool'],
        ['linkTool', 'unlinkTool'],
        ['imageTool','emojiTool'],
        ['tableTool'],
        ['findTool'],
        ['cleanTool']
      ]  
     });`

报错:
`Uncaught [TextBusError: Tool]: tool type is not supported.
    at t.createHandler (http://www.test7.com/static/textbus/textbus.min.js:24:176580)
    at http://www.test7.com/static/textbus/textbus.min.js:24:175753
    at Array.map (<anonymous>)
    at t.createHandlers (http://www.test7.com/static/textbus/textbus.min.js:24:175727)
    at http://www.test7.com/static/textbus/textbus.min.js:24:175488
    at Array.forEach (<anonymous>)
    at t.createToolbar (http://www.test7.com/static/textbus/textbus.min.js:24:175370)
    at new t (http://www.test7.com/static/textbus/textbus.min.js:24:172564)
    at http://www.test7.com/static/textbus/textbus.min.js:1:12754`

**Comment by tbhuabi** [comment]
textbus 和其它富文本不一样哦，这里传的不是字符串，而是一个工具对象，看你这个报错，应该是通过 script 标签使用的，工具条应该像下面这样

```js
textbus.createEditor(document.getElementById('editor'), {
  toolbar: [
    [textbus.historyBackTool, textbus.historyForwordTool]
  ]
})
```

**Comment by zuozuoba** [comment]
哦哦，感谢~



---原始邮件---
发件人: "TanBo"<notifications@github.com&gt;
发送时间: 2021年2月8日(周一) 凌晨0:05
收件人: "tbhuabi/textbus"<textbus@noreply.github.com&gt;;
抄送: "zhangzhibin"<954861399@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [tbhuabi/textbus] 直接引用js, 定制toolbar时出错 (#32)




 
textbus 和其它富文本不一样哦，这里传的不是字符串，而是一个工具对象，看你这个报错，应该是通过 script 标签使用的，工具条应该像下面这样
 textbus.createEditor(document.getElementById('editor'), {   toolbar: [     [textbus.historyBackTool, textbus.historyForwordTool]   ] })
