### ISSUE TITLE
【软件BUG】插入代码时应该清除格式

### ISSUE THREAD

**Issue by hyfree** [textbus/textbus#35]
1、粘贴代码的时候清除格式。或者右键粘贴纯文本。

举例：
从https://textbus.tanboui.com/doc/components复制一段带格式的代码字符串，然后粘贴到textbus。

![image](https://user-images.githubusercontent.com/26597853/117738365-7076b680-b22e-11eb-8d7d-051eaedd0504.png)

**Comment by hyfree** [comment]
此问题的前置条件是#36

**Comment by textbus** [comment]
太过久远了，欢迎关注新版动态
