### ISSUE TITLE
【软件BUG】首行无法插入代码块组件和表格组件

### ISSUE THREAD

**Issue by hyfree** [textbus/textbus#36]
描述：
首行无法插入代码块组件、表格组件。
步骤：
1、打开https://textbus.tanboui.com/
2、Ctrl+A全选，然后删除编辑器的全部内容
3、点击菜单栏 插入代码组件后 编辑器无法正在显示代码块组件的编辑区域。
4、表格组件同上。

![image](https://user-images.githubusercontent.com/26597853/117738473-af0c7100-b22e-11eb-92c9-24ac5664fda4.png)

![image](https://user-images.githubusercontent.com/26597853/117738691-36f27b00-b22f-11eb-9323-aeafa2044a7b.png)

**Comment by tbhuabi** [comment]
谢谢你的反馈，问题已修复，请升级至 1.0.0-beta.54

**Comment by textbus** [comment]
太过久远了，欢迎关注新版动态
