### ISSUE TITLE
【软件功能】代办列表支持tab

### ISSUE THREAD

**Issue by hyfree** [textbus/textbus#37]
描述：希望支持使用TAB键把任务列表往后退4个空格距离
现在的：
![image](https://user-images.githubusercontent.com/26597853/117739049-095a0180-b230-11eb-9ea2-94c51369194a.png)
软件功能：
![image](https://user-images.githubusercontent.com/26597853/117739489-0c092680-b231-11eb-9f71-85879670a280.png)

**Comment by textbus** [comment]
太过久远了，欢迎关注新版动态
