### ISSUE TITLE
关于组件库中有弹框交互的组件，点击“取消”按钮，控制台提示报错的情况讨论

### ISSUE THREAD

**Issue by ghost** [textbus/textbus#4]
## 复现步骤
1. 点击有预先弹窗的组件（如百度地图）

![image](https://user-images.githubusercontent.com/57755075/89714668-dfd72580-d9d2-11ea-8ec9-7c60be134380.png)

2. 点击弹窗内的取消按钮

![image](https://user-images.githubusercontent.com/57755075/89714609-85d66000-d9d2-11ea-95e0-17655c97c811.png)

3. 看控制台，提示报错

![image](https://user-images.githubusercontent.com/57755075/89714647-c635de00-d9d2-11ea-9f5f-8d123ccf53aa.png)

## 版本
当前的 master 和 develop c37fe7a7a820eefae9e3c461e3e50280f1494c5b

## 分析
以百度地图组件为例

1. 在 `src\lib\lib\additional-components\baidu-map.component.ts` 文件下 L109-113 ，在关闭弹窗时会执行 reject()
![image](https://user-images.githubusercontent.com/57755075/89714706-39d7eb00-d9d3-11ea-94d6-3b21f3519b1f.png)

2. 在 `src\lib\lib\workbench\component-stage.ts` 文件下 L40，有一个 addExample 方法，这个方法在 `src\lib\lib\workbench\component-stage.ts` 下 L158-160 Editor 的构造函数下，每个组件都会执行这个方法，大概是初始化（？）

3. addExample 方法下，有一段绑定点击事件的代码，其中 L46-49 这里只有 then 的拦截，reject 未作处理直接抛出。由于我不知道的原因，生产环境这个错误很难去跟踪

![image](https://user-images.githubusercontent.com/57755075/89714856-36912f00-d9d4-11ea-842d-f8da4ec505bd.png)

![image](https://user-images.githubusercontent.com/57755075/89715046-802e4980-d9d5-11ea-855c-71b32219aa08.png)

## 提问

1. 查看类似的弹框组件，如 element-ui 、antd 等，均有点击确定 resolve，点击取消 reject 的设计。咱们这个也是同样的设计，这种设计的初衷是什么？

2. 因为咱们弹框组件的 reject 没有被用户管理，因此有必要区分点击取消按钮的 reject 和组件内部错误的 reject 吗？点击取消按钮是操作正常流程，应该不需要抛出错误吧？

**Comment by tbhuabi** [comment]
谢谢你的关注！给你造成困扰感到非常抱歉。
回答你的问题：
如果以一个整体来看，确实如你提问的第二点所说，没必要 reject。即可以在组件弹窗取消的时候，不调用 reject。但如果从软件设计上来看，这里就分成了两部分，就叫作框架和组件吧。

从框架层面说，是不知道外部的组件会有什么逻辑，把错误抛出来，让组件设计者看到，而不是作其它预设处理，是一个比较好的实践。
从组件设计来说，是不知道框架内部是怎么实现的，只是按需返回框架所需要的数据。但当点击取消的时候，按理说，是没有正常返回一个组件实例的，所以调用 reject 是没错的。

当然，以上只是我个人的见解，如有不周，还请见谅！

另外，从产品角度，我觉得你说的很有道理。我后面看一下，把这种错误封装得更友好一点，以免你说的生产环境很难排查。
