### ISSUE TITLE
光标指向对图片有异常

### ISSUE THREAD

**Issue by 312307025** [textbus/textbus#40]
鼠标只有在图片右方点击，光标才会指向图片后面
![微信截图_20210719152352](https://user-images.githubusercontent.com/17807336/126119704-3e1ebe00-1615-40ce-8b7e-d31d4bc10dc1.png)
而右上方与右下方都是指向文字后面
![微信截图_20210719152424](https://user-images.githubusercontent.com/17807336/126119945-e242eeea-cb85-4af8-b4c9-f9c919382a06.png)

而且我希望图片可以设置vertical-align 属性设置元素的垂直对齐方式，不然图片与文字对齐蛮奇怪的。

**Comment by textbus** [comment]
最新3.0 版本可以支持你要的功能，欢迎你来验证一下
