### ISSUE TITLE
看，怎么优化这个问题

### ISSUE THREAD

**Issue by iCloudys** [textbus/textbus#42]
![图片](https://user-images.githubusercontent.com/13017318/129151122-d9a3ac17-9e2e-4ff3-a0ad-aa8aa5d3882a.png)

**Comment by textbus** [comment]
textbus 不支持移动端的

**Comment by iCloudys** [comment]
这么快，这个不是移动端，是在一个比较小的div上展示不全

**Comment by textbus** [comment]
这个主是要为了防止 ui 溢出，所以，范围被限制在了 textbus 编辑器的大小内

**Comment by iCloudys** [comment]
工具条上的弹框能插入到body里面吗

**Comment by textbus** [comment]
这个只有改工具条的源码（https://github.com/textbus/toolbar/blob/main/src/toolbar/toolkit/_api.ts ）才能实现了，你可以自己改一下自用，但通用库，可能不会改了

**Comment by iCloudys** [comment]
换插件了
