### ISSUE TITLE
如何自定义工具条的UI

### ISSUE THREAD

**Issue by iCloudys** [textbus/textbus#43]
![图片](https://user-images.githubusercontent.com/13017318/129152745-dccc37d9-1c55-40fe-a070-042492fcc20a.png)
如何改变工具条上面按钮的样式，比如颜色、大小、更换图标、更换文字等

**Comment by textbus** [comment]
每一个工具，在源代码内都有导出一个 config 文件的，直接修改就好了，至于样式，直接修改 css

**Comment by textbus** [comment]
![image](https://user-images.githubusercontent.com/84023794/129153275-8582a9b5-eaa5-4f1d-a747-e4f206a1a29d.png)
这里就是加粗工具的配置项

**Comment by iCloudys** [comment]
ok
