### ISSUE TITLE
点击上传图片时，按钮马上就变成了 loading 状态，如果不进行选择文件，这个loading状态会一直存在

### ISSUE THREAD

**Issue by HJianfeng** [textbus/textbus#45]
![image](https://user-images.githubusercontent.com/17350820/135041076-6ed6839b-1d30-494a-b220-31e5e7226a1e.png)
不选择文件，直接点击取消
![image](https://user-images.githubusercontent.com/17350820/135041147-cbddce79-9546-4e4c-acf5-0b29155ea4c7.png)
按钮的loading会一直存在

**Comment by textbus** [comment]
加个事件，在 body focus 的时候，返回一个 Promise.reject()
