### ISSUE TITLE
【优化建议】颜色取色时，面板容易关闭问题，是否可优化？

### ISSUE THREAD

**Issue by Damao2250** [textbus/textbus#46]
颜色取色时，点击取色快中圆点拖动到纯白色位置时，鼠标容易跑出取色面板外，此时放开鼠标取色面板会关闭，需要重新点击取色，然后点击确定才能正确选择颜色，特别是对于初次使用的人好像不太友好。

**Comment by textbus** [comment]
好的，会尽快优化

**Comment by textbus** [comment]
你好，这个问题已改了，你看一下官网，现在的版本是否符合你的预期
