### ISSUE TITLE
从word复制粘贴后部分样式丢失及源代码编辑卡顿问题

### ISSUE THREAD

**Issue by dancebear** [textbus/textbus#5]
从word复制一个包含带框线的表格到编辑器内，表格的框线全部丢失，且无法设置框线颜色，切换到源代码模式编辑，编辑器直接卡死！
操作系统：macOS 10.15.6，浏览器：chrome 84.0.4147.135

**Comment by tbhuabi** [comment]
已修复表格边框失效的问题，请更新至0.0.1-beta.28。
源代码模式卡顿属已知问题，目前不推荐使用。同时，我们正在寻找可行的解决方案，会尽快解决些问题，谢谢你的关注！
如有兴趣参与，也可通过官网加群，直接沟通！
