### ISSUE TITLE
在移动端富文本软键盘不能弹出

### ISSUE THREAD

**Issue by 635503281** [textbus/textbus#50]
在ios移动端访问页面，该富文本不能弹出软键盘！！！
估计光标也不准确

**Comment by textbus** [comment]
你好，当前版本不支持移动端哦！
欢迎持续关注 textbus，下一个版本将会兼容移动端，且支持协同编辑

**Comment by LainNetWork** [comment]
请问现在支持移动端了么？需要兼容移动端我应该使用v1还是测试中的v2?

**Comment by tbhuabi** [comment]
你好，要兼容移动端要使用v2，但目前只开发了&nbsp;PC&nbsp;端中间层，还没有开发移动端的中间层，2.0的内核设计是可以跨端跨平台的。如果你有兴趣了解更多，或参与移动端中间层开发，我们可以细聊。
你也可以参考现在的 packages/browser&nbsp;模块，里面是&nbsp;PC&nbsp;端中间层的代码。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月25日(星期二) 上午10:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [textbus/textbus] 在移动端富文本软键盘不能弹出 (Issue #50)





 
请问现在支持移动端了么？需要兼容移动端我应该使用v1还是测试中的v2?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by textbus** [comment]
textbus 3.0 已支持移动端，需在配置项配置 useContentEditable: true。
