### ISSUE TITLE
【软件BUG】输入区域被内容撑开后，再删除内容，被撑开的区域会一直那么大的BUG

### ISSUE THREAD

**Issue by HJianfeng** [textbus/textbus#53]
![image](https://user-images.githubusercontent.com/17350820/140446589-da055ddf-8951-4c1a-baaa-2df12fa9162d.png)

![image](https://user-images.githubusercontent.com/17350820/140446659-974ab3a6-afac-4c8e-84d1-4ef60e503215.png)

**Comment by textbus** [comment]
谢谢，知道了

**Comment by textbus** [comment]
新版本已不会有这个问题了。
