### ISSUE TITLE
【软件BUG】查找功能无法正常使用

### ISSUE THREAD

**Issue by hyfree** [textbus/textbus#54]
# 描述

1 搜索“textbus”在输入字母t的时候，光标焦点直接飞到了搜索结果的位置，无法输入完整的textbus搜索关键词

![image](https://user-images.githubusercontent.com/26597853/143155021-af2fc0b8-6541-4245-9155-cba7bdae967f.png)

2 再次使用查找功能时无反应

![image](https://user-images.githubusercontent.com/26597853/143156156-86b7aee7-0673-4510-9e94-1b6b0e805d82.png)

# 涉及版本
https://textbus.tanboui.com/ 官网最新版本

**Comment by textbus** [comment]
1.0 版本已不再维护，请使用 Textbus 新版本
