### ISSUE TITLE
如果要基于textbus实现修改痕迹怎么做？

### ISSUE THREAD

**Issue by soonwait** [textbus/textbus#6]

**Comment by tbhuabi** [comment]
请详细描述你的需求，最好有场景的示例和图片说明

**Comment by tbhuabi** [comment]
由于太长时间没有得到你的回复，你提的问题又是一个很开放的问题，在此基础上不能得到明确的需求和功能点，故先关闭此问题，如果你确实需要实现你所描述的功能，欢迎再次与我们联系。
