### ISSUE TITLE
看起来很棒! 没有MIT或者类似授权码?

### ISSUE THREAD

**Issue by edwinyzh** [textbus/textbus#62]
试了一下官网的demo, 功能似乎很全, 而且组件扩展功能似乎很强, 感谢作者的贡献.
问一下授权问题, 没有MIT或者类似的协议吗? 想要商用有何选项? 谢谢.

**Comment by Yangjia23** [comment]
+1

**Comment by textbus** [comment]
太过久远了，欢迎关注新版动态
