### ISSUE TITLE
在服务器上运行时，当我第二次进入编辑器时就报错了

### ISSUE THREAD

**Issue by DbPtZn** [textbus/textbus#65]
![$7@GZ%$SME$ LZ)@4_TJ Q](https://user-images.githubusercontent.com/59691454/157274462-4443faad-1d61-459d-aeb5-9f2e173f425c.png)

这种情况在本地跑时不会出现。

**Comment by textbus** [comment]
你好，新版本已更改这部分实现，不会报错了
