### ISSUE TITLE
工具条面板失焦无法关闭的问题

### ISSUE THREAD

**Issue by ghost** [textbus/textbus#7]
问题描述：
当工具条的面板打开时，点击内容输入区域，面板无法关闭，比如 链接 的面板，打开之后，点击工具条的空白区域，可以关闭，但是点击内容输入区域则无法关闭。

问题描述图片：
![image](https://user-images.githubusercontent.com/58690804/96094513-039d7700-0f00-11eb-91d9-9c76003dbacc.png)

期望结果：
希望在点击内容输入区域时，关闭已经打开的面板

**Comment by tbhuabi** [comment]
我本地测试了一下，没有重现，能不能提供一些更具体的信息
浏览器版本：
操作系统：
Textbus版本：
编辑框内的内容：
操作步骤：

**Comment by tbhuabi** [comment]
由于太长时间没有得到你的回复，另现在测试并未发现此问题，所以暂时先关闭这个问题。
