### ISSUE TITLE
在dialog中，切换字体 刷新当前页面

### ISSUE THREAD

**Issue by io-o** [textbus/textbus#89]
vue3 + element-plus, 使用dialog内嵌编辑器，切换字体导致页面刷新
"@textbus/editor": "^2.6.0"
"vue": "^3.2.39",
"element-plus": "2.2.22",
![动画](https://user-images.githubusercontent.com/22197685/211230565-9ec7673a-718c-456f-8156-86e732a4e148.gif)

**Comment by io-o** [comment]
切换字体，会自动在url后面追加?，导致刷新

**Comment by io-o** [comment]
切换字体会触发 表单默认提交事件， 需要表单上加 @submit.prevent，阻止下就可以

**Comment by textbus** [comment]
谢谢反馈，明天修复

**Comment by textbus** [comment]
bug 已修复，请安装安装 2.6.3 版本
<img width="227" alt="image" src="https://user-images.githubusercontent.com/84023794/212315528-b46b7598-e159-42a8-83f2-2172f32acfdd.png">
