### ISSUE TITLE
卡片组件bug：当编辑区域卡片组件位于文档开头时，Ctrl+A 无法选中编辑区域全部内容，并报 textbus.min.js:24 Uncaught TypeError: Cannot read property 'getContentAtIndex' of undefined 错误

### ISSUE THREAD

**Issue by ghost** [textbus/textbus#9]
## 操作环境

-   textbus 版本: 公测版 0.1.0-alpha.5
-   组件及版本 (如果是组件相关问题): 卡片组件
-   浏览器及运行版本: XXX

[**NOTE**: 如果你正在使用旧版本 textbus，建议升级到最新版本，可能在新版本中已经解决了这个问题 ]

## 期望行为

可正常选择编辑区域全部内容

## 当前行为

当编辑区域卡片组件位于文档开头时，Ctrl+A 无法选中编辑区域全部内容，并报 textbus.min.js:24 Uncaught TypeError: Cannot read property 'getContentAtIndex' of undefined 错误

![image](https://user-images.githubusercontent.com/74443578/99350444-5d1b0c00-28d9-11eb-8c5e-798e7b04e7a6.png)

## 可复现问题的操作步骤

[**NOTE**: 请提供最小化可复现问题的代码片段，这将会对定位与排查问题 **非常** 有帮助 ]

1. 清空编辑区域的文本内容
2. 从右侧组件区域选择卡片组件。此时卡片组件将呈现在编辑区域
3. 激活编辑区域，在键盘上按 Ctrl+A

## 日志

<details>

<summary>请将错误日志粘贴在下方。点击前面的三角号可展开/折叠日志信息
</summary>

<p>

```javascript
Uncaught TypeError: Cannot read property 'getContentAtIndex' of undefined
    at t.findFirstPosition (textbus.min.js:24)
    at t.findFirstPosition (textbus.min.js:24)
    at t.selectAll (textbus.min.js:24)
    at Object.action (textbus.min.js:24)
    at e._next (textbus.min.js:24)
    at e.__tryOrUnsub (textbus.min.js:16)
    at e.next (textbus.min.js:16)
    at e._next (textbus.min.js:16)
    at e.next (textbus.min.js:16)
    at e._next (textbus.min.js:55)
```

</p>
</details>

**Comment by tbhuabi** [comment]
谢谢你提交的问题，现已修复，请更新至 @tanbo/textbus@0.1.0-alpha.6
https://github.com/tbhuabi/textbus/commit/8a6f6defa26c5de06ecacc5bd6677ed248110a51
