### ISSUE TITLE
表格复制粘贴后内容丢失

### ISSUE THREAD

**Issue by zzj946** [textbus/textbus#91]

**Comment by huangliyun02** [comment]
复制表格，新复制生成的表格单元格会错位，该如何解决？
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/57118533/236871809-b679eb23-8a9e-4887-9275-6633f60cb773.png">

原因是表格的第一个单元格被插入了一个br元素，导致后面的单元格位置就错乱了

**Comment by textbus** [comment]
太过久远了，欢迎关注新版动态
