### ISSUE TITLE
请问3.0版本的文档还有么

### ISSUE THREAD

**Issue by liuyu2018** [textbus/textbus#95]
如题，求3.0文档地址

**Comment by textbus** [comment]
访问这个分支：https://github.com/textbus/textbus.io/tree/v3.0
克隆下来，然后安装依赖，启动服务

**Comment by liuyu2018** [comment]
好的，谢谢大佬，祝万事顺遂！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月20日(周五) 上午10:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [textbus/textbus] 请问3.0版本的文档还有么 (Issue #95)




 
访问这个分支：https://github.com/textbus/textbus.io/tree/v3.0，克隆下来，然后安装依赖，启动服务
