### ISSUE TITLE
sanitizeHtml过滤富文本的内容，哪些应该被放行？

### ISSUE THREAD

**Issue by pionear-layen** [textbus/textbus#96]
如题，还请看下疑问，谢谢。

**Comment by textbus** [comment]
你参考一下 loader 的相关文档，textbus 识别 HTML，全由 loader 实现，不需要像其它富文本有专门的程序

**Comment by pionear-layen** [comment]
大佬，能给下指引吗，感觉资料有点少呢

**Comment by textbus** [comment]
textbus 的输出是由你写的 formatter 或 component 的渲染代码决定的，完全可控。
输入能识别什么，是由 loader 决定的，如果没有写对应 HTML 的 loader，那么这部分 HTML 就不会被识别。

**Comment by textbus** [comment]
太过久远了，欢迎关注新版动态
