### ISSUE TITLE
请问可以进入源代码编辑模式吗

### ISSUE THREAD

**Issue by StarOfLife** [textbus/textbus#97]
如题，3.7.2版本的编辑器可以进入源代码编辑模式将提前编辑好的html代码复制进去，然后再切回富文本编辑模式吗

**Comment by textbus** [comment]
你好，不支持源代码编辑模式哦，Textbus 有约定的数据格式，由于源代码模式没有可控性，编辑源代码并不能无损转换成 Textbus 的数据结构。并且引入源代码编辑模式，还有历史记录，协作等问题无法处理。因 Textbus 不会默认不会支持。
当然，你可以自己定制，功能肯定是可以实现的（在 Textbus 1.0 的时候，是有支持源代码编辑模式的）。

**Comment by textbus** [comment]
太过久远了，欢迎关注新版动态
