### ISSUE TITLE
【求助】当前最新可用版本是什么？

### ISSUE THREAD

**Issue by wan-kong** [textbus/textbus#98]
想请问一下，当前最新可用版本是多少？
我看最新的4.0仍然在alpha状态。
但是文档和vue-demo已经更新到了4.0.alpha.x
而且看起来alpha扔在更新新功能。
目前我想将textbus做为基础服务封装一层，请问下我应该选择哪个版本呢？

谢谢：）

**Comment by textbus** [comment]
你好，稳定版本是 3.* 的版本，但 4.0 无疑是更好的选择，目前 4.* 基本形态应该不会发生大的改变，但还未经完全稳定，如果你想基于 textbus 做二次开发，可以尝试使用 4.0 的版本。
4.0 是在 3.* 基础上做了一些对开发者更友好的设计，全面拥抱前端框架，有更好的开发体验。
